#!/usr/bin/env bash
# This script configures the nginx server so that /redirect_me is redirecting to
# another page.

# Install nginx
sudo apt update
sudo apt install nginx -y

# Configure firewall
sudo ufw allow 80

# Configure root webpage
echo 'Hello World!' | \
    sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Set redirection
sed -i '/listen 80 default_server/a rewrite ^/redirect_me \https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
