#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  alex-frontend
        bind *:80
        mode http
        default_backend udo-backend
backend udo-backend
        balance roundrobin
        server 137342-web-01 18.207.139.229:80 check
        server 137342-web-02 100.26.49.225:80 check
"
echo "${server_config}" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart haproxy
sudo service haproxy restart
