#!/usr/bin/env bash
# A Bash script that displays lines containing the `bash` word.
# shellcheck disable=SC2009

BASH_IDs="$(pidof bash)"
ps -uhf "$BASH_IDs"

# This script displays lines containing the bash word, thus allowing
# you to easily get the PID of your Bash process.
