#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
#     display hours from 0 to 12
#     display minutes from 1 to 59
# Requirements:
#     You must use the while loop (for and until are forbidden)

HOUR="0"

while [ "$HOUR" -le "12" ];
do
    echo "Hour: $HOUR"

    MINUTE="1"
    while [ "$MINUTE" -lt "60" ];
    do
	echo "$MINUTE"
	MINUTE=$((MINUTE + 1))
    done

    HOUR=$((HOUR + 1))
done
