#!/usr/bin/env bash
# A bash script that installs the ufw firewall and setup a few rules on a server
# Requirements:
# - It blocks all incoming traffic, except the following TCP ports
#   22 (SSH), 443 (HTTPS), 80 (HTTP)

# Install
sudo apt-get update -y
sudo apt-get install -y ufw

# Configure 1
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing
# Configure 2
sudo ufw allow 22/tcp       && \
sudo ufw allow 443/tcp      && \
sudo ufw allow 80/tcp       && \

sudo ufw enable             && \
echo "

---> DONE ---
"
# sudo ufw disable
# sudo ufw enable
