#!/usr/bin/env bash
# Fixes a web server to run nginx as nginx user (not root user) listening on port 8080

# Set a user in the config by replacing '#user' and it's value
sudo sed -i s/'#user www-data'/'user nginx'/ /etc/nginx/nginx.conf

# Modify nginx config file: replace 80 with 8080
sudo sed -i s/'80'/'8080'/ /etc/nginx/sites-enabled/default

# Grant read/write permission to the owner
sudo chmod 644 /etc/nginx/nginx.conf

# Apache may interfere with nginx so kill it if its running
pkill apache2

# Restart nginx (not as root)
sudo -u nginx service nginx start
